version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_log_to_discord_local_django
    container_name: django_log_to_discord_local_django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:9000"
    command: /start

  docs:
    image: django_log_to_discord_local_docs
    container_name: django_log_to_discord_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_log_to_discord:/app/django_log_to_discord:z
    ports:
      - "7000:7000"
    command: /start-docs

  celeryworker:
    <<: *django
    image: django_log_to_discord_local_celeryworker
    container_name: django_log_to_discord_local_celeryworker
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: django_log_to_discord_local_celerybeat
    container_name: django_log_to_discord_local_celerybeat
    ports: []
    command: /start-celerybeat
